let mongoose = require('mongoose')

let allRightModule = new mongoose.Schema({
 empId:String,
 empName:String,
 memBerId:String,
 email:String,
 emailUniqId:String,
 crmRights:{
    crmDashboard:{
        value:Boolean,
        rights:[]
    },
    crmEmployee:{
        value:Boolean,
        items:{
            crmDashboard1:{
                value:Boolean,
               rights:[]
            },
            crmEmployeeTarget1:{
                value:Boolean,
                rights:[]
            },
            crmMemberCalls1:{
                value:Boolean,
                rights:[]
            },crmSalesCall1:{
                value:Boolean,
                rights:[]
            },crmServicesRateCard1:{
                value:Boolean
            }
        }
    },
    crmTrainer:{
        value:Boolean,
        items:{
            superRight:{
                dailybatchAttendance:[],
                monthlyReport:[],
                clientAttendanceReg:[]
            },    
            crmLiveClasses1:{
                value:Boolean
            },
            crmAllBatches1:{
                value:Boolean
            },
            crmPtClasses1:{
                value:Boolean
            },
            crmTtcClasses:{
                value:Boolean
            },
            crmAllMembers1:{
                value:Boolean
            }
        }
    },
    crmLeads:{
        value:Boolean,
        items:{
            superRight:{
                addOn:[],
                delete:[],
                edit:[]
            },
            crmAllEnquiry1:{
                value:Boolean,
            },
            crmAppointment1:{
                value:Boolean,
            },
            crmTrialUpdate1:{
                value:Boolean,
            },
            crmProspects1:{
                value:Boolean,
            },
            crmCallsReports1:{
                value:Boolean,
            },
            crmColdEnquires1:{
                value:Boolean,
            }
        }
    },
    crmCientManagment:{
        value:Boolean,
        items:{
            superRight:{
                delete:[],
                edit:[],
                status:[],
                profile:[]
            },
            crmAllClients1:{
                value:Boolean,
            },
            crmActiveClients1:{
                value:Boolean,
            },
            crmRenewalsClient1:{
                value:Boolean,
            },
            crmRenewedClients1:{
                value:Boolean,
            },
            crmLeftClients1:{
                value:Boolean,
            },
            crmClientSupport1:{
                value:Boolean,
            }
        }
    },
    crmMarketing:{
        value:Boolean,
        items:{
            superRight:{
                addOn:[],
                delete:[],
                edit:[],
                status:[],
            },
            crmEmailMarketing1:{
                value:Boolean
            },
            crmSmsMarketing1:{
                value:Boolean
            },
            crmPushMarketing1:{
                value:Boolean
            },
            crmBulkMailerData1:{
                value:Boolean
            },
            crmBulkCallingData1:{
                value:Boolean
            },
            crmCustomerReview1:{
                value:Boolean
            },
            crmOffersMaster1:{
             value:Boolean
            }
        }
    },
    crmFitness:{
        value:Boolean,
         superRight:{
            addOn:[],
            delete:[],
            edit:[],
            access:[],
        },
        items:{
            crmFitnessGoal:{
                value:Boolean,
                rights:[]
            }
        }
    }
 }
}, { timestamps: true })

module.exports = mongoose.model('allRightModule', allRightModule);
